### ISSUE TITLE
tray on gnome?

### ISSUE THREAD

**Issue by soloturn** [PonasKovas/netctl-tray#1]
when using it on gnome it says:

```
$ netctl-tray 
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QObject::connect: No such signal QPlatformNativeInterface::systemTrayWindowChanged(QScreen*)
```

QT_QPA_PLATFORM is set. and no tray icon appears. i saw https://bugreports.qt.io/browse/QTBUG-31762 though which suggests that there was a bug long time ago, but should be fixed nowadays.

**Comment by PonasKovas** [comment]
Could you please specify more information about your machine? What OS? Which version of Gnome?
Do you have any other applications with working tray icons?

**Comment by soloturn** [comment]
arch linux, latest of all. i am not sure if network manager would count, it worked, now i removed it to make netctl-auto work. if you tell me one i will try it.

**Comment by PonasKovas** [comment]
Which version if Qt do you have installed?
`pacman -Q qt5`

Lots of applications use the tray. I can easily think of these: Discord, SimpleScreenRecorder, Redshift.

**Comment by xzinkus** [comment]
Should close this due to inactivity @PonasKovas. After #4 merges, this will be tested working on Gnome shell 3.34.1.
