### ISSUE TITLE
PermissionDenied, message: "Permission denied" solved

### ISSUE THREAD

**Issue by ghost** [PonasKovas/netctl-tray#10]
getting a repeating error message.

Can't update tray state: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
Can't update tray state: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
Can't update tray state: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
Can't update tray state: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
Can't update tray state: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
Can't update tray state: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
Can't update tray state: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
Can't update tray state: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
Can't update tray state: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }

I am part of the network group and wheel

Version: 0.2.1

in /etc/sudoers

%wheel ALL=(ALL) ALL

uncommitted I don't know if that matters. I type in the sudo password every time.

**Comment by PonasKovas** [comment]
Are you using `netctl` or `netctl-auto`? which version?

Does it work with sudo?

**Comment by PonasKovas** [comment]
What is the output of this command?
```
stat /etc/netctl/
```

**Comment by ghost** [comment]
netctl-tray 0.2.1. It kinda works with sudo I can change networks but the info is not displayed. When I load it with the user I do not get an error message telling me I am not part of the wheel group or network. I am running arch Linux kernel 4.19.131-1-lts419. I installed netctl-tray via the aur repository. It was the latest version. I am running cinnamon desktop.

sudo netctl-tray

No dbus error message tell I left click on the tray icon to get more info about the connection. 

Warning! You are not in group 'wheel', netctl-tray might not work or work only partially.
Warning! You are not in group 'network', netctl-tray might not work or work only partially.
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Error sending desktop notification: Error { kind: Dbus(D-Bus error: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead (org.freedesktop.DBus.Error.NotSupported)) }
Error sending desktop notification: Error { kind: Dbus(D-Bus error: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead (org.freedesktop.DBus.Error.NotSupported)) }



stat /etc/netctl/
 File: /etc/netctl/
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: 801h/2049d	Inode: 2098427     Links: 5
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-05-21 03:21:41.000000000 -0700
Modify: 2020-07-03 15:11:02.609162734 -0700
Change: 2020-07-03 15:11:02.609162734 -0700
 Birth: 2020-05-21 03:21:41.956146527 -0700

**Comment by ghost** [comment]
Great little program by the way if only I could get it to work on my system. For years I have been using NetworkManager and always had issues with it. netctl just works but it feels like I am missing something with no tray icon lol.

**Comment by PonasKovas** [comment]
Are you sure you're in `network` and `wheel`?
Could you run this command just to make sure?

```sh
sudo usermod -a -G wheel,network <user>
```

What is the output of this command?
```sh
netctl list
```

**Comment by ghost** [comment]
I ran "sudo usermod -a -G wheel,network <user>" again same error message.

$ groups
network power autologin rfkill users storage audio wheel

$ netctl list
  
 wlp2s0-itek
* wlp2s0-itek5
  wlp2s0-AppleNet

netctl is working I am connected to wlp2s0-itek5.

**Comment by PonasKovas** [comment]
What about this command?
```sh
cat /proc/net/wireless
```

**Comment by ghost** [comment]
$ cat /proc/net/wireless
Inter-| sta-|   Quality        |   Discarded packets               | Missed | WE
 face | tus | link level noise |  nwid  crypt   frag  retry   misc | beacon | 22
wlp2s0: 0000   56.  -54.  -256        0      0      0      0      8        0

**Comment by ghost** [comment]
thanks for taking  the time to help me by the way.

**Comment by PonasKovas** [comment]
No problem!

Try running this shell script:
```sh
for file in /etc/netctl/*
do
  stat $file | grep Access
done
```

**Comment by ghost** [comment]
$ ./test.sh 
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-05-22 01:25:34.000000000 -0700
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-05-22 01:25:34.000000000 -0700
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-05-22 01:25:34.000000000 -0700
Access: (0600/-rw-------)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-07-03 15:10:40.004188093 -0700
Access: (0600/-rw-------)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-07-03 15:11:02.609162734 -0700
Access: (0600/-rw-------)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-05-22 01:27:58.494014607 -0700

**Comment by PonasKovas** [comment]
Yep that's the problem

**Comment by PonasKovas** [comment]
You have 3 profiles with `600` permissions and owned by root

**Comment by PonasKovas** [comment]
So your user doesn't even have permission to read those profiles

**Comment by PonasKovas** [comment]
```sh
sudo chmod 644 /etc/netctl/*
```

**Comment by ghost** [comment]
Your a genius thanks for you help I never thought of that. It works now. I just used sudo wifi-menu to make the profiles no wonder they were owned by root.
