### ISSUE TITLE
Ping doesn't work with a VPN

### ISSUE THREAD

**Issue by gfarrell** [PonasKovas/netctl-tray#11]
I use mullvad as my VPN. If it is connected (which it always is), the icon shows a little exclamation mark and clicking on the icon shows an infinite ping.

If I disconnect the VPN then the icon loses the exclamation mark, the ping works properly, etc..

VPN connected:
![icon when vpn is connected](https://user-images.githubusercontent.com/314331/91455140-04137d00-e882-11ea-949c-03f9ccc58c25.png)

VPN disconnected:
![icon when vpn is disconnected](https://user-images.githubusercontent.com/314331/91455212-1a213d80-e882-11ea-9b85-9f7eed3c0030.png)

**Comment by PonasKovas** [comment]
Could you try running this command? What is it's output?
```sh
ping 1.1.1.1
```
(With the VPN on)

**Comment by gfarrell** [comment]
Pinging that works fine, it's my go to for checking connectivity (ping times are long because I have a rubbish connection).

```
~ > ping 1.1.1.1
PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
64 bytes from 1.1.1.1: icmp_seq=1 ttl=56 time=648 ms
64 bytes from 1.1.1.1: icmp_seq=2 ttl=56 time=630 ms
64 bytes from 1.1.1.1: icmp_seq=3 ttl=56 time=551 ms
64 bytes from 1.1.1.1: icmp_seq=4 ttl=56 time=656 ms
64 bytes from 1.1.1.1: icmp_seq=5 ttl=56 time=656 ms
```

**Comment by PonasKovas** [comment]
Yep that's the problem. If the ping is more than 500ms, `netctl-tray` just assumes there's no internet and shows infinite ping.

**Comment by PonasKovas** [comment]
I'll try to think of a solution

**Comment by gfarrell** [comment]
That can't be it, I just tried pinging again:

```
~ > ping 1.1.1.1
PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
64 bytes from 1.1.1.1: icmp_seq=1 ttl=61 time=45.1 ms
64 bytes from 1.1.1.1: icmp_seq=2 ttl=61 time=121 ms
64 bytes from 1.1.1.1: icmp_seq=3 ttl=61 time=46.8 ms
64 bytes from 1.1.1.1: icmp_seq=4 ttl=61 time=47.1 ms
64 bytes from 1.1.1.1: icmp_seq=5 ttl=61 time=60.2 ms
```

`netctl-tray` is still showing infinite ping times.

**Comment by gfarrell** [comment]
I'm not sure if it helps but I'm using `netctl-tray-auto` from the AUR.

**Comment by gfarrell** [comment]
Ok so I've tested this with a little programme just for fun and found the issue.

According to the [Mullvad ToS](https://mullvad.net/en/help/terms-service/) they block requests to port 53 to prevent DNS leaks as a security measure.

Given this, might I suggest we use port 80 by default since this is open on 1.1.1.1 and therefore shouldn't make any difference to the programme itself? I'll open a PR.

**Comment by gfarrell** [comment]
PR here: https://github.com/PonasKovas/netctl-tray/pull/12/files

**Comment by PonasKovas** [comment]
I just now realized that for some reason this program doesn't actually ping the host, but instead tries to open a TCP connection, which was bound to introduce problems. The correct solution to this problem is to ping using the ICMP hello packet.

As a temporary solution you can specify the 80 port with the `--host` flag: `netctl-tray-auto --host 1.1.1.1:80`

**Comment by PonasKovas** [comment]
ba6d98508436a9d1868e3eb8f5418fc3512a53ff the latest commit should fix this issue

Feel free to re-open if you encounter any more issues
