### ISSUE TITLE
Support netctl-auto

### ISSUE THREAD

**Issue by xzinkus** [PonasKovas/netctl-tray#2]
Hi! Thank you for developing this, especially seeing as all of the gnome extension packages which try to add system trays for netctl are outdated and broken.

I wanted to request support for netctl-auto. As it is, `netctl list` doesn't list any active profiles when netctl-auto is managing things. `sudo netctl-auto list` will, but it requires root for some reason probably specific to netctl.

I'm working on a PR, but if you're willing to do it, that'd be better. Thanks!

**Comment by PonasKovas** [comment]
Hey,

I'm kinda working on another project right now so it would be perfect if you could make the PR.

**Comment by xzinkus** [comment]
@PonasKovas If you could check #3 and then #4, and merge if approved, I'd be very grateful! Tested working on gnome-shell 3.34.1 on Ubuntu.

**Comment by xzinkus** [comment]
I closed #4 per our discussion. I'll look at what's needed to address this properly in a way that makes more sense, i.e. polkit to enable `netctl-auto` instead of `sudo` and `#[cfg]`-based compilation between the functionality I split between `netctl-tray` and `netctl-auto-tray`.

Leaving this issue open to track progress and comments.

**Comment by xzinkus** [comment]
Can I ask why in a107c628d09df66320a73a266219f57e59b2b888 you changed from `switch-to` to `start` and `stop`?

**Comment by PonasKovas** [comment]
I don't know, it was very long ago, but I think `switch-to` doesn't work when no profile is active? I could be wrong

**Comment by PonasKovas** [comment]
Nope, it works. I think it was because the polkit rule doesn't allow "switch-to", because I forgot to add it, and then I thought that it doesn't work for other reasons, so i just replaced it with stop and start. I will probably fix this today.

**Comment by xzinkus** [comment]
Awesome, thanks. I’ll use it going forward too.

**Comment by xzinkus** [comment]
Side note: https://aur.archlinux.org/packages/netctl-auto-tray/ Unfortunate that someone forked already and used the name. Looks like they just run `netctl-tray` as root.

**Comment by PonasKovas** [comment]
I think that they will agree to give the name

**Comment by xzinkus** [comment]
PolKit note-to-self: write a script for `start / stop / switch-to` and `list`, drop it in `scripts/`, install to `/usr/share/netctl-tray/`, and then use a `org.freedesktop.policykit.exec` policy for them. `exec` doesn't authorize program arguments, so anything else is unsafe.

**Comment by xzinkus** [comment]
@PonasKovas I'll write this PR, it'll be fun :) (also, this isn't the place, but let me know what you think of the new colorful icons).

**Comment by PonasKovas** [comment]
They look better than the old ones for sure

**Comment by PonasKovas** [comment]
@maxzinkus Any progress?

**Comment by xzinkus** [comment]
Not at all, I'm sorry. The whole pandemic situation has reduced my free time significantly. I can possibly get to this over the upcoming summer. Apologies.

**Comment by ghost** [comment]
just send me a message if this is ready and I'll orphan my AUR package

**Comment by xzinkus** [comment]
Alright, gonna open a PR

**Comment by PonasKovas** [comment]
I just tried out netctl-auto myself, and turns out it doesn't even need root permissions haha!

All it needs is for the user to be in `wheel` group.

I'm working on the refactored version, I hope soon I'll be able to push it.

**Comment by PonasKovas** [comment]
It is done :)

@mortzu as I understand you've orphaned the AUR package already? Thanks

**Comment by ghost** [comment]
Not yet. Just give me a hint

**Comment by PonasKovas** [comment]
Oh haha I used the name `netctl-tray-auto` instead of `netctl-auto-tray`. You can orphan your package now to avoid confusion

**Comment by ghost** [comment]
done

**Comment by ghost** [comment]
Please adopt the package

**Comment by ghost** [comment]
Any reaction?

**Comment by PonasKovas** [comment]
@mortzu I am using the name [`netctl-tray-auto`](https://aur.archlinux.org/packages/netctl-tray-auto/)
