### ISSUE TITLE
iwconfig is a hidden (and depreacated?) dependency

### ISSUE THREAD

**Issue by DjebbZ** [PonasKovas/netctl-tray#5]
Hi,

I've just stumbled your package, decided to try it, but it failed when I launched it :

```
> netctl-tray
thread 'main' panicked at 'failed to run iwconfig: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/main.rs:280:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Because I don't have `iwconfig`. A quick search in the Arch Wiki led me to https://wiki.archlinux.org/index.php/Network_configuration/Wireless#iw_and_wireless_tools_comparison, where the first line states that `iw replaces iwconfig`. I'm sure of the status of `iw`/`iwconfig`, but maybe I know I have `iw` installed on my machine and not `iwconfig`.

Not sure of the solution: should you try both before failing? Use `iwconfig` instead?

Happy to help review as much as I can.

Btw, I'm using Arch and netcl, up-to-date of course.

**Comment by PonasKovas** [comment]
Hi, I'm pretty sure that you got it wrong, `iw` is not replacing `iwconfig`. `iw` is provided by [iw](https://www.archlinux.org/packages/core/x86_64/iw/), and `iwconfig` is provided by [wireless_tools](https://www.archlinux.org/packages/core/x86_64/wireless_tools/), and they both exist in peace with each other.

I think that `iwconfig` is more popular than `iw`, and `iw` seems to require root permissions for the most simple operations, which would be hard to set up on netctl-tray, therefore I see no reason to support `iw`.

For now, I think I'll just add `wireless_tools` as a dependency.

**Comment by PonasKovas** [comment]
Done.

If you have any more questions or anything, feel free to reopen this issue.

**Comment by DjebbZ** [comment]
I rebooted, uninstalled and reinstalled and it works just fine now apparently. Not sure whether the reboot or the reinstallation fixed it, but at least it's fixed!
Thanks for your tool and your quick response.
