### ISSUE TITLE
netctl-tray doesn't detect that my user is in wheel group

### ISSUE THREAD

**Issue by sauraveldho** [PonasKovas/netctl-tray#8]
![IMG_20200627_015124](https://user-images.githubusercontent.com/47508447/85897844-cc07a380-b818-11ea-9625-0783ef5c5265.jpg)

On Arch, Wayland, Sway with Xwayland disabled.

**Comment by sauraveldho** [comment]
On Arch-Wayland-Sway

**Comment by sauraveldho** [comment]
Do I have to run this as sudo everytime?...seems to work if I run as sudo!

**Comment by PonasKovas** [comment]
Oh man this is embarrassing
https://github.com/PonasKovas/netctl-tray/blob/master/src/main.rs#L288-L293

Add your user to the `network` group and it should work, I'll try to sort the code out to give proper warnings.

**Comment by PonasKovas** [comment]
Feel free to reopen if you have any further issues or questions
